### ISSUE TITLE
Typo in "How to write a customized environment?" page

### ISSUE THREAD

**Issue by takasho777** [JuliaReinforcementLearning/JuliaReinforcementLearning.github.io#9]
At the end of The minimal interfaces to implement section in "How to write a customized environment?" page, there is the following test code.
```
using ReinforcementLearning
hook = TotalRewardPerEpisode()
run(
    Agent(
        ;policy = RandomPolicy(env),
        trajectory = VectorialCompactSARTSATrajectory(
            state_type=Bool,
            action_type=Any,
            reward_type=Int,
            terminal_type=Bool,
        ),
    ),
    LotteryEnv(),
    StopAfterEpisode(1_000),
    hook
)

println(sum(hook.rewards) / 1_000)
```

Should ```VectorialCompactSARTSATrajectory``` be replaced by ```VectCompactSARTSATrajectory```? It looks ```VectorialCompactSARTSATrajectory``` is not defined in ReinforcementLearningCore (v0.4.5).

Also, its output is shown as
```
UndefVarError: env not defined
```
which seems unintentional. There is another UndefVarError at the beginning of the Traits of environments section too.

**Comment by findmyway** [comment]
Thanks for reporting!

I think I've wrongly tagged a release of ReinforcementLearningCore.jl, a patch release instead of a minor release. I'll fix the doc ASAP.

The UndefVarError is caused by that ReinforcementLearningBase is not inluded in the root Project.toml file. I need to check Franklin.jl again to see if it supports different environments now in each folder.
